# Generated by Django 3.2.9 on 2024-10-16 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20241016_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(blank=True, max_length=42, null=True, validators=[django.core.validators.MinLengthValidator(42)]),
        ),
    ]
