# Generated by Django 4.2.9 on 2024-02-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'attribute',
            },
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('fk_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.attribute')),
                ('fk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.item')),
            ],
            options={
                'db_table': 'item_atrribute',
            },
        ),
    ]
