# Generated by Django 4.2.9 on 2024-02-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_itemattribute_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemattribute',
            table='item_attribute',
        ),
    ]
